### ISSUE TITLE
Enhancement request: DisconnectTo / DisconnectFrom

### ISSUE THREAD

**Issue by carlbeech** [ppaez/alsaseq#9]
Hi

Apologies if this isn't the correct forum, I'm fairly new at this...

I came across your alsaseq library, and I'm trying to use it in a project that I'm working on - I've been able to use the connectto and connectfrom and send the correct data, however, can you let me know how I remove the connections using the library? Basically, a 'disconnectto' and 'disconnectfrom'...?
I can basically do this by performing a shell-call to 'aconnect -d...' however, that isn't so great...

Hopefully the above makes sense - or am I missing something in the way you're supposed to use the library...

Many thanks

Carl.

**Comment by ppaez** [comment]
@carlbeech Adding disconnectto and disconnectfrom to the alsaseq module is a useful idea. I will work on the changes and let you know when they are ready.  Thanks for suggesting this!

Regards,
Patricio

**Comment by ppaez** [comment]
@carlbeech I tested disconnectto and disconnectfrom, added to the interactive use documentation and pushed the changes.   Please let me know results of using on your side.

**Comment by carlbeech** [comment]
Hi

Many - many thanks for the very fast turnaround - that is really
appreciated!

I'll try to put the updates through the paces - it'll be a couple of days
before I can get time to work on my code, but I'll feed back as soon as I
can..

Many thanks again

Carl.

**Comment by carlbeech** [comment]
Hi

Just to confirm that the disconnectto is working in my code... I've tried
disconnectFrom and this appears to be working also - many thanks for the
alteration !  :-D

For info, my program is called 'MidiChooser', and it allows you to connect
up to nine Qsynth ports up to a keyboard, and connect / disconnect as you
need - I play 'live' in a band, so don't have time to select different
sounds, so using this, I can pre-define up to nine different sounds - each
one in a different sound engine, and switch them on and off at will.

Previously, I had to shell out of python and run 'aconnect' to perform a
disconnect - and I can now do this properly in code...  :-)

The only bit I need to shell out for now is to perform aconnect -li and
aconnect -lo to list the input and output ports (I set the instrument names
within QSynth, and my program picks this up when doing an 'aconnect -lo'..

Many thanks

Carl.

**Comment by ppaez** [comment]
Closing this as completed.  Enhancement request #10 was created to address the need for knowing which client and port numbers are available

**Comment by carlbeech** [comment]
Hi Patricio

Just to let you know - I had to rebuild my environment, and so I did a pip3
install alsaseq - however, while it said that I had got 0.4.2, it was
missing the disconnectto enhancements (and I'm guessing others?)

I've downloaded the Zip from Github, did a build and install and its
working ok.

I'm guessing something is missing in that your updates haven't made it to
pip?

Just thought you may want to double check - its been a while since I've
done some active python work, so I may have missed a step.

All the best

Carl.
